export const dummy = [
    {   
      id: 1,
    merchant_address:  "33 patrick bokkor, Jabi Abuja",
    merchant_category_colorcode:  "tomato",
    merchant_category_id:  2,
    merchant_category_marker:  "https://www.pikpng.com/pngl/b/547-5478780_restaurant-cutlery-circular-symbol-of-a-spoon-and.png",
    merchant_category_name:  "Food",
    merchant_email:  "onipetheoderic@gmail.com",
    merchant_id:  1,
    merchant_latitude: 9.1266,
    merchant_longitude: 7.431,
    merchant_logo: "",
    merchant_name: "Chicken Republic",
    merchant_phone: "07039148866",
    merchant_website: "www.google.com",
    coupon_image: "https://www.freepik.com/free-photo/meat-burger-french-fries-spices-side-view_7652215.htm",
    coupon_description: "Buy 4 Chicken Get 1 for Free"
  },
  {   
    id: 2,
  merchant_address:  "33 patrick bokkor, Jabi Abuja",
  merchant_category_colorcode:  "tomato",
  merchant_category_id:  2,
  merchant_category_marker:  "https://www.pikpng.com/pngl/b/547-5478780_restaurant-cutlery-circular-symbol-of-a-spoon-and.png",
  merchant_category_name:  "Food",
  merchant_email:  "onipetheoderic@gmail.com",
  merchant_id:  1,
  merchant_latitude: 9.226,
  merchant_longitude: 7.431,
  merchant_logo: "",
  merchant_name: "Chicken Republic",
  merchant_phone: "07039148866",
  merchant_website: "www.google.com",
  coupon_image: "https://image.freepik.com/free-photo/meat-burger-tomato-onion-beans-walnuts-side-view_141793-2391.jpg",
  coupon_description: "Buy 4 Chicken Get 1 for Free"
},
{   
  id: 6,
merchant_address:  "33 patrick bokkor, Jabi Abuja",
merchant_category_colorcode:  "tomato",
merchant_category_id:  2,
merchant_category_marker:  "https://www.pikpng.com/pngl/b/547-5478780_restaurant-cutlery-circular-symbol-of-a-spoon-and.png",
merchant_category_name:  "Food",
merchant_email:  "onipetheoderic@gmail.com",
merchant_id:  1,
merchant_latitude: 9.216,
merchant_longitude: 7.441,
merchant_logo: "",
merchant_name: "Chicken Republic",
merchant_phone: "07039148866",
merchant_website: "www.google.com",
coupon_image: "https://www.freepik.com/free-psd/food-social-media-promotion-instagram-banner-post-design-template_10314963.htm",
coupon_description: "Buy 4 Chicken Get 1 for Free"
},
{   
id: 3,
merchant_address:  "33 patrick bokkor, Jabi Abuja",
merchant_category_colorcode:  "tomato",
merchant_category_id:  2,
merchant_category_marker:  "https://www.pikpng.com/pngl/b/547-5478780_restaurant-cutlery-circular-symbol-of-a-spoon-and.png",
merchant_category_name:  "Food",
merchant_email:  "onipetheoderic@gmail.com",
merchant_id:  1,
merchant_latitude: 9.086,
merchant_longitude: 7.531,
merchant_logo: "",
merchant_name: "Chicken Republic",
merchant_phone: "07039148866",
merchant_website: "www.google.com",
coupon_image: "https://image.freepik.com/free-photo/crispy-french-fries-with-ketchup-mayonnaise_1150-26588.jpg",
coupon_description: "Buy 4 Chicken Get 1 for Free"
},
{   
id: 4,
merchant_address:  "33 patrick bokkor, Jabi Abuja",
merchant_category_colorcode:  "tomato",
merchant_category_id:  2,
merchant_category_marker:  "https://www.pikpng.com/pngl/b/547-5478780_restaurant-cutlery-circular-symbol-of-a-spoon-and.png",
merchant_category_name:  "Food",
merchant_email:  "onipetheoderic@gmail.com",
merchant_id:  1,
merchant_latitude: 9.076,
merchant_longitude: 7.531,
merchant_logo: "",
merchant_name: "Chicken Republic",
merchant_phone: "07039148866",
merchant_website: "www.google.com",
coupon_image: "https://image.freepik.com/free-photo/side-view-doner-with-grilled-chicken-greens-lettuce-tomato-french-fries-table_141793-4881.jpg",
coupon_description: "Buy 4 Chicken Get 1 for Free"
}
  ]